const ENCODING_TYPE = 'base64';
const VERIFICATION_TOKEN_EXPIRES_AT = 1; // in hours
const MAX_FILE_NAME_LENGTH = 64;

module.exports = {
	ENCODING_TYPE,
	VERIFICATION_TOKEN_EXPIRES_AT,
	MAX_FILE_NAME_LENGTH,
};
